### PR TITLE
replace readFileSync

### PR DESCRIPTION
**Pull request by Yanpas**
I decided to do it sequentially to keep the same behaviour and predictable memory consumption.

### CODE REVIEW

**Comment by skovhus** [comment]
I realize now that using the `fs.promises` API means that we limit the support to node 10+.

So either we should:
1) Update the required node version here https://github.com/bash-lsp/bash-language-server/blob/master/server/package.json#L18
2) Use the `util.promisify()` API (node 8) as you originally suggested

Thoughts?

**Comment by Yanpas** [comment]
I think the second one is better. Ubuntu 18.04 ships 8th lts version e.g.

**Comment by skovhus** [comment]
Let us go with 2 then. 👍 I’ll update CI to test on node 8.

**Comment by skovhus** [comment]
Replaced by https://github.com/bash-lsp/bash-language-server/pull/213

**Pull request merged**
