### PR TITLE
Snippets update: add more snippets and change their naming convention

### LINKED ISSUE #781: Add snippet for documenting functions (I will implement)
### What is the problem this feature will solve?

Speed up documenting functions.

### What is the feature you are proposing to solve the problem?

Snippet for a function doc, like this:

```md
# ${1:function_name} ${2:function_parameters}
# ${3:function_description}
#
# Output:
#   ${4:function_output}
#
# Return:
# - ${5:0} when ${6:all parameters are correct}
# - ${7:1} ${8:otherwise}
```

Having such doc is useful as intellisence can show it on hovering on function names. As Bash lacks strict typing docs is one of convenient ways to present what functions expect and what returns.

### What alternatives have you considered?

_No response_

### PR DESCRIPTION
**Pull request by EmilySeville7cfg**
- document all snippets via `documentation`
- add snippets for commands like `if` with `[[` command
- add more `sed` and `awk` snippets
- change naming convention to make labels more descriptive (but longer)
- add snippet for function doc (closes #781)
- snippets for jq, yq

### CODE REVIEW

**Comment by EmilySeville7cfg** [comment]
@skovhus, what to do with [these](https://github.com/bash-lsp/bash-language-server/actions/runs/4562553154/jobs/8049923478?pr=805#step:6:11) failures?

**Review by skovhus — APPROVED** [review]

**Comment by Shane-XB-Qian** [comment]
@EmilySeville7cfg
those `if-else.test` and `while.test` was verified and worked at your side?

**Comment by EmilySeville7cfg** [comment]
@Shane-XB-Qian, yep. ;) I've checked them.

**Comment by EmilySeville7cfg** [comment]
> would you mind change those - and . delimiters in if-else.test (uniformed) to _, e.g 'if_else_test` ?

I can change it to `-` for now. Hoply send PR today or tomorrow to fix this issue. Didn't know about such problem with Vim.

**Pull request merged**
