### PR TITLE
Fuzzy search workspace symbols 

### PR DESCRIPTION
**Pull request by skovhus**
Related https://github.com/mads-hartmann/bash-language-server/issues/197

@przepompownia rightfully identified that workspace symbols are more useful if they are resolved using fuzzy search.

### CODE REVIEW

**Comment by przepompownia** [comment]
Please do not automatically close #197 by resolving only the matching problem. That issue contains also the problem of discoverability by the client.

**Comment by skovhus** [comment]
@przepompownia I've updated this to use fuzzy search. Please try it out if you have time. :)

**Comment by przepompownia** [comment]
I'm trying to take advantage of the fact that we have the opportunity to work at the same time.

This request takes lot of CPU usage and does not want to end. It looks that I have to manually kill node process :) The next step will be trying to preview what happens.

**Comment by przepompownia** [comment]
It was happen without fetching the new package. I only compiled the changes fom this PR.

**Comment by przepompownia** [comment]
It works after fetching the new dependency :)

I have added primitive git hooks in .githooks (with `core.hooksPath`) that runs `yarn` and `yarn run compile` but I had to run them manually after getting forced update.

**Pull request merged**
